version: '3.1'

services:
  app:
    build: .
    volumes:
      - ./src/:/usr/src/app
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: 'development'
      DEBUG: 1
      FLASK_DEBUG: 1
      PAYMENTS_LOGIN: empty
      PAYMENTS_PASSWORD: empty
      EMAIL_HOST: smtp_server
      EMAIL_PORT: 2525
      EMAIL_USERNAME: none
      EMAIL_PASSWORD: none
      EMAIL_FROM_NAME: SMP
      EMAIL_FROM_ADDRESS: admin@smp.io
      DB_DSN: postgresql://postgres:clone@database:5432/smp_db
      REDIS_HOST: redis
    depends_on:
      - database
      - smtp_server
      - redis
      - worker

  database:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: clone
      POSTGRES_DB: smp_db
    ports:
      - "5432:5432"

  smtp_server:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
    environment:
      - MH_SMTP_BIND_ADDR=0.0.0.0:2525

  redis:
    image: redis:5
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"

  worker:
    image: app
    command: rq worker -u "redis://redis:6379"
    volumes:
      - ./src:/usr/src/app
    environment:
      FLASK_ENV: 'development'
      DEBUG: 'true'
      FLASK_DEBUG: 'true'
      PAYMENTS_LOGIN: empty
      PAYMENTS_PASSWORD: empty
      EMAIL_HOST: smtp_server
      EMAIL_PORT: 2525
      EMAIL_USERNAME: none
      EMAIL_PASSWORD: none
      EMAIL_FROM_NAME: SMP
      EMAIL_FROM_ADDRESS: admin@smp.io
      DB_DSN: postgresql://postgres:clone@database:5432/smp_db
      REDIS_HOST: redis
      DB_ECHO: 'true'
    depends_on:
      - redis

#  ghost:
#    image: emilol/ghost-cloudinary
#    restart: always
#    ports:
#      - "2368:2368"
#    volumes:
#      - $INSTALL_PATH/content:${GHOST_INSTALL:-/var/lib/ghost}/content
#      - $INSTALL_PATH/content.orig:${GHOST_INSTALL:-/var/lib/ghost}/content.orig
#      - $CONFIG_PATH:${GHOST_INSTALL:-/var/lib/ghost}/config.production.json
#    environment:
#      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME:?run export CLOUDINARY_CLOUD_NAME="your cloud name"}
#      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY:?run export CLOUDINARY_API_KEY="your api key"}
#      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET:?run export CLOUDINARY_API_SECRET="your api secret"}
#    command: "bash -c \"su-exec node ghost config storage.cloudinary-store.cloud_name '$CLOUDINARY_CLOUD_NAME'; \
#                        su-exec node ghost config storage.cloudinary-store.api_key '$CLOUDINARY_API_KEY'; \
#                        su-exec node ghost config storage.cloudinary-store.api_secret '$CLOUDINARY_API_SECRET' &> /dev/null; \
#                        node current/index.js\""
#  localtunnel:
#    image: node:10-alpine
#    command: npx localtunnel --port 2368 --local-host ${GHOST_HOST:-localhost} --subdomain ${GHOST_SUBDOMAIN}
#    depends_on:
#      - ghost
