version: '3.4'

services:
  app:
    image: modulith_app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src/:/usr/src/app
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: 'development'
      DEBUG: 1
      FLASK_DEBUG: 1
      PAYMENTS_LOGIN: empty
      PAYMENTS_PASSWORD: empty
      EMAIL_HOST: smtp_server
      EMAIL_PORT: 2525
      EMAIL_USERNAME: none
      EMAIL_PASSWORD: none
      EMAIL_FROM_NAME: SMP
      EMAIL_FROM_ADDRESS: admin@smp.io
      DB_DSN: postgresql://postgres:clone@database:5432/smp_db
      REDIS_HOST: redis
      MINIO_HOST: minio:9000
      MINIO_ACCESS_KEY: Q3AM3UQ867
      MINIO_SECRET_KEY: Vh5smyLeyCZd^$$4m9pmb7T16!DwyU18kvPJFiCSG
    depends_on:
      - database
      - redis
      - nginx

  database:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: clone
      POSTGRES_DB: smp_db
    ports:
      - "5432:5432"

  smtp_server:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
    environment:
      - MH_SMTP_BIND_ADDR=0.0.0.0:2525

  redis:
    image: redis:5
#    volumes:
#      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"

  rq_worker:
    image: modulith_app
    working_dir: /usr/src/worker
    command: [ "/usr/local/bin/rq", "worker", "-u", "redis://redis:6379" ]
    volumes:
      - ./src:/usr/src/worker
    environment:
      FLASK_ENV: 'development'
      DEBUG: 1
      FLASK_DEBUG: 1
      PAYMENTS_LOGIN: empty
      PAYMENTS_PASSWORD: empty
      EMAIL_HOST: smtp_server
      EMAIL_PORT: 2525
      EMAIL_USERNAME: none
      EMAIL_PASSWORD: none
      EMAIL_FROM_NAME: SMP
      EMAIL_FROM_ADDRESS: admin@smp.io
      DB_DSN: postgresql://postgres:clone@database:5432/smp_db
      REDIS_HOST: redis
      DB_ECHO: 'true'
    depends_on:
      - smtp_server
      - redis
      - app

  minio:
    image: minio/minio
    hostname: minio
    volumes:
      - ../data:/data
    expose:
      - "9000"
    environment:
      MINIO_ROOT_USER: Q3AM3UQ867
      MINIO_ROOT_PASSWORD: Vh5smyLeyCZd^$$4m9pmb7T16!DwyU18kvPJFiCSG
    command: minio server /data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

  nginx:
    image: nginx
    hostname: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:9000"
    depends_on:
      - minio