version: '3.1'

services:
  api:
    image: master-image
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src/:/usr/src/app
    ports:
      - "5000:5000"
    env_file: ./master_image.env
    command: /usr/local/bin/flask run --host=0.0.0.0
    depends_on:
      - database
      - redis
      - nginx

#  rq_worker:
  #    image: master-image
  #    command: /usr/local/bin/rqworker -n extra_worker_001 -u redis://redis:6379/0 -v
  #    env_file: ./master_image.env
  #    depends_on:
  #      - smtp_server
  #      - redis

  rq_dashboard:
    image: master-image
    ports:
      - 5555:5555
    depends_on:
      - redis
    command: /usr/local/bin/rq-dashboard --port 5555 --redis-url redis://redis:6379/0

  test_app:
    image: master-image
    env_file: ./master_image.env
    depends_on:
      - smtp_server
      - redis

  database:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: clone
      POSTGRES_DB: smp_db
    ports:
      - "5432:5432"

  smtp_server:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
    environment:
      - MH_SMTP_BIND_ADDR=0.0.0.0:2525

  redis:
    image: redis:5
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"

  minio:
    image: minio/minio
    hostname: minio
    volumes:
      - ../data:/data
    expose:
      - "9000"
    environment:
      MINIO_ROOT_USER: Q3AM3UQ867
      MINIO_ROOT_PASSWORD: Vh5smyLeyCZd^$$4m9pmb7T16!DwyU18kvPJFiCSG
    command: minio server /data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

  nginx:
    image: nginx
    hostname: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:9000"
    depends_on:
      - minio