INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_PXPkHnyTCy1mNRxnIPL7.2UqPi', 'Albania', 'AL');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_4IH2sx4Lby2TKGJSKrha.WaDB5', 'Algeria', 'DZ');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_6wVfEB2aJ7Srp7KPETlg.beOoR', 'American Samoa', 'AS');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_AjRhlU0g5V6s8m0B703H.71dUV', 'Andorra', 'AD');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_nrRcpkKgxOGrfrqM9fiW.nIQsd', 'Angola', 'AO');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_Vy3GOlRO6nZDPfnYt2u2.VaW4G', 'Anguilla', 'AI');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_lX5msNLMolNOf0goegwI.tsmzh', 'Antarctica', 'AQ');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_bBDq3hp2eeLBrgs5OA6P.GAMxg', 'Antigua and Barbuda', 'AG');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_wagWZfJO3rXoQmclZgd8.CZ6il', 'Argentina', 'AR');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_SUypkZfoWI81fsEK1dS7.uCZHh', 'Armenia', 'AM');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_hBqiVIRi4jbK6AawGvIQ.rkcjj', 'Aruba', 'AW');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_LzzBaIXC9B7MWVF9VuWi.Gu5nM', 'Australia', 'AU');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_4NNCBfGAY7pYaIbOQ4rV.BM0HW', 'Austria', 'AT');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_8se3ofNx1j3PwVDlmubc.J3FXi', 'Azerbaijan', 'AZ');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_ZUNWu06XDYP89nv2FDXx.QDi14', 'Bahamas', 'BS');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_tsGXEesIDcT0RDG9L01c.HKBmk', 'Bahrain', 'BH');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_LbXxqpxqAOM22uxwDaIY.X6hMz', 'Bangladesh', 'BD');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_iiaL0xBakD59MRdCloEq.poetv', 'Barbados', 'BB');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_bwosMtOYLNoSFmqPpiWi.qcCN6', 'Belarus', 'BY');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_vVRqaf2AvLVEvoLo0ZHJ.eXV20', 'Belgium', 'BE');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_GaqiZWasJmV66h5pWE6x.tYqGe', 'Belize', 'BZ');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_KckovnWGngzUzDhAUVWE.JkhBi', 'Benin', 'BJ');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_SETqCwUCPvMS9jFnvXlx.oWClO', 'Bermuda', 'BM');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_MOs1IrKgmvYEeTnEARPt.gQnq4', 'Bhutan', 'BT');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_Rlx3j4vzZUSLOBQWpREI.YxUN2', 'Bolivia', 'BO');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_HBS1tX1S6s6i9FWSa9dv.iixn5', 'Botswana', 'BW');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_8EJXc52kzUFUbkTMcPH9.VK7tb', 'Brazil', 'BR');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_lK8IA4SO5pIJxG4bcyWM.LJgbv', 'British Indian Ocean Territory', 'IO');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_doWuOUkuWMrBBgeoqKNZ.aH3OE', 'British Virgin Islands', 'VG');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_GO4v2PcYcUVNx04IJrEi.2pySg', 'Brunei', 'BN');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_iEDLLpHts23wmSrA3Grp.Fhvdr', 'Bulgaria', 'BG');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_i2RaKhCpOtSSAHaKKCVD.otGxw', 'Burkina Faso', 'BF');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_tMUukKvgkMBjV0RfRWC8.1Vbhj', 'Burundi', 'BI');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_7d1KwgBaUjyFHWuQtHzT.o89ZL', 'Cambodia', 'KH');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_HlfNcopS0J4rktUvQjHz.xVdUr', 'Cameroon', 'CM');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_3oKB5lKXB2IPI5qzZOfN.H2W3K', 'Canada', 'CA');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_w8aEiBGRGi09f68mbky8.YzXwf', 'Cape Verde', 'CV');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_v2l4hil4ZyULp129icbt.ICC5O', 'Cayman Islands', 'KY');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_V75myaVmiMnNpqgff0P6.kVl7o', 'Central African Republic', 'CF');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_bLPwSpp9e6hMdMj84EwF.ytHuZ', 'Chad', 'TD');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_5s3J2NsiUrAcBaUcENMF.it9ot', 'Chile', 'CL');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_nu44mw76HT1ieAA1WnvC.HtQ2V', 'China', 'CN');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_ZTXyitOXDUu52Z1ASDPK.MdIBp', 'Christmas Island', 'CX');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_CUDoKajidJhAJq0UwyVp.sKdxQ', 'Cocos Islands', 'CC');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_hWZuoHDpdFSTCuyeljkA.cjnUx', 'Colombia', 'CO');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_aJYUQgDm6ddGwsETKX4l.JCy9B', 'Comoros', 'KM');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_X2Bxq04lOj2DjdHjV5E4.bnqga', 'Cook Islands', 'CK');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_kYKGBvIU5sFxd5uCUdcR.CYKfI', 'Costa Rica', 'CR');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_ZE9gDNMWgumGasQSVtdl.pewnK', 'Croatia', 'HR');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_ZU9hcrYgZuBuYGdjYwwf.ljF2w', 'Cuba', 'CU');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_G1xM26Kvy2zOtRmcM70B.f2pDY', 'Curacao', 'CW');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_8bj9Gos79CxT79xrn7Tz.A6qVx', 'Cyprus', 'CY');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_UMo6k7minhu5u3EcRaf8.AcEUN', 'Czech Republic', 'CZ');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_AWuYNZ4BQRGxNwHlDFqq.KR4nM', 'Democratic Republic of the Congo', 'CD');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_2N7it0ZhFzGkndChMaqu.kwrnr', 'Denmark', 'DK');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_HnbKApAzzD4bBDMQuQr6.fnLSt', 'Djibouti', 'DJ');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_N4cPOkbdXoAscN9CM01y.CYLbF', 'Dominica', 'DM');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_VgYf1IqxmQaANiPn5jJW.REtaZ', 'Dominican Republic', 'DO');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_XJMy3OBSV1Bde1209Rrb.rQsMt', 'East Timor', 'TL');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_S6kqAdRCUAn7aMq8W9RO.m5ome', 'Ecuador', 'EC');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_Rj2eJjkUYemDn3sjAyWa.jUsmD', 'Egypt', 'EG');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_Q9qBu6yb2MTGNLiUDgpC.xTBR2', 'El Salvador', 'SV');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_IgFmy1c3ajDioPPpFMXy.mcQs7', 'Equatorial Guinea', 'GQ');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_kR2rNwq0qugSPVPfxHln.66CJy', 'Eritrea', 'ER');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_5QbaqzARxLH7tZqcWxBQ.GyKtT', 'Estonia', 'EE');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_UdfWCyyzUgcNyqqSWNQ2.g7lYI', 'Ethiopia', 'ET');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_fGLxfiUiXg7rG4RK1o8A.O4IGQ', 'Falkland Islands', 'FK');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_uaK9PQQZgsip46B9IJN5.jm9jk', 'Faroe Islands', 'FO');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_KnBQ55FnsZpxxzwnAu0y.9EOJS', 'Fiji', 'FJ');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_0ireTTEAVch1HJsgC1Me.Hccl0', 'Finland', 'FI');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_DXiNqUfniyDSQoGUAubL.WuH2v', 'France', 'FR');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_qzZQ2GZzBtqZzZsJMCyK.sAEAD', 'French Polynesia', 'PF');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_ClYu6nBEpMPCd6AbgG1z.KTSmI', 'Gabon', 'GA');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_GhI1NcS6yZHNzRVYplYR.wWFXX', 'Gambia', 'GM');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_8cC0eVu4qCamxcDYDmNP.TrNsG', 'Georgia', 'GE');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_OU6LNGwzfwXYyBk4q1M1.ujAsc', 'Germany', 'DE');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_0aEnpLISbCfAnchA3myy.Gjp5b', 'Gibraltar', 'GI');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_R85FG6U5bDQ5OEoVuO46.JrkGy', 'Greece', 'GR');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_Nlh8IyN5YJCRLopzzgcD.cAUcb', 'Greenland', 'GL');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_OPrKTIUjiHrjpPcgDaHv.QdDn5', 'Grenada', 'GD');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_6lUIE1NZkjAqn1iuiwYw.CUJ9g', 'Guam', 'GU');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_qqe5Q4fT7yPd2bAYrEOF.8ojDb', 'Guatemala', 'GT');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_78madcArNflvRs87AnJh.6Egt0', 'Guernsey', 'GG');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_I945fuxJj3LMz9qCxDp3.HazI9', 'Guinea', 'GN');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_2UzhHtlf6JYfnWqR2POB.E8Fwe', 'Guinea-BissauGW', 'undefined');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_cPfbPkoRWvUh89rh3oV7.OZZ5z', 'Guyana', 'GY');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_4PebxUFgXMqpdSpp8V0X.N4vLP', 'Haiti', 'HT');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_6lydH9tb87bABPYPS5yn.FyoEZ', 'Honduras', 'HN');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_WIQebrRMKaElLiBk0ETH.Kzzdq', 'Hong Kong', 'HK');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_5a0S1eO2G9U6Ugt8MqIr.BDzuh', 'Hungary', 'HU');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_v4xJOGaUqa6gYSl8KhJA.4VVtJ', 'Iceland', 'IS');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_6bacbcGnkxLrtWcihPYA.vqaqN', 'India', 'IN');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_FTCgLkmPYDrc8I9hq6nE.jW1Ol', 'Indonesia', 'ID');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_yi6Te4GV1062ajM1Mwsr.smahA', 'Iran', 'IR');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_Rwwjy7gwCv0sxQt2balv.gXGkn', 'Iraq', 'IQ');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_nHdBOtlA7kZEGlB0GBbC.IcLkY', 'Ireland', 'IE');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_tEVFQWCvmpcgtbB0N9Zj.2AFUW', 'Isle of Man', 'IM');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_A4FXSBblcrRfbctO4hZb.DV8HT', 'Italy', 'IT');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_kZT9k4kEsm5qS3hCrTSR.SevRj', 'Ivory Coast', 'CI');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_udvyYJr6dxwaK5LVWmXT.O1f9K', 'Jamaica', 'JM');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_diYoRfanKjRpcViaRV71.RjaW6', 'Japan', 'JP');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_NDu6Vb1PGMh3RPN3TJuK.xj2JG', 'Jersey', 'JE');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_lGz34fmrNJPV7yGCrQVa.GiMZG', 'Jordan', 'JO');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_zL5LQVC42WAyPXy5IaU1.csXRG', 'Kenya', 'KE');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_BQKhHbNJhQfe5EoJh2ot.wSJoL', 'Kiribati', 'KI');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_5IBY11wpr47QBTLs3PXn.Mu5qQ', 'Kosovo', 'XK');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_zzIXU5WzY1nBHQuzf2hc.fSUfZ', 'Kuwait', 'KW');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_HGQABeerSWQHLD2ZAxMI.NWlmr', 'Kyrgyzstan', 'KG');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_hA6GScEucyNedaUKi8eQ.hIV3s', 'Laos', 'LA');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_VDfpi73x9yBe7M8QTRNp.b3n55', 'Latvia', 'LV');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_bKVmwS4YCNLiGw5cVaxF.7Ok1R', 'Lebanon', 'LB');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_RQoc1U0AZBgLu07lIdf6.WaOMn', 'Lesotho', 'LS');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_DohAWmAhCYiYFPoHJcFL.1rCzJ', 'Liberia', 'LR');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_XYiVltTiMHstWy8T8cKS.vjyGJ', 'Libya', 'LY');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_U9NQbokagWjQ73XLSjZC.INBlG', 'Liechtenstein', 'LI');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_jjHtfhDTZmL6Pe0aRWV6.p8Cfa', 'Lithuania', 'LT');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_GAjRio2HRk6256YMJSYO.BrDPF', 'Luxembourg', 'LU');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_P9u3NIOuQGsDDUvOEx7l.KfMtL', 'Macau', 'MO');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_85ySOdNmsAfzBrf9DgEJ.tknE6', 'Macedonia', 'MK');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_n0YEFIdY41wk6wVxBvYo.j8MlY', 'Madagascar', 'MG');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_oQDuyIVUFPx5BQteEc1H.i1tSm', 'Malawi', 'MW');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_xz0hA6Pk7WFrdrMx4yZM.dKYdR', 'Malaysia', 'MY');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_DlT6na3TT4zWqUvPCQNF.niiki', 'Maldives', 'MV');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_cyOPHAtZ9rKcEEVeRENj.zUe8V', 'Mali', 'ML');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_TKLl9VnApShvV32CBkex.4fXoq', 'Malta', 'MT');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_9VgTj6j0FgnMvh0wydLb.GNuvU', 'Marshall Islands', 'MH');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_oBIsNZgX7HvBwKxmvz3E.Mj42t', 'Mauritania', 'MR');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_qO8HSyRamXv7EfIhDQB6.WB0ur', 'Mauritius', 'MU');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_1gBJJ84fFwB5HgiHmfKd.sGY0i', 'Mayotte', 'YT');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_rRf6mUf8QPhv3x8vK67U.Mtkui', 'Mexico', 'MX');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_XZz6srKtpSmGd6lkrWfv.emDSy', 'Micronesia', 'FM');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_x51Eff2CRniJQntY62nx.IWL00', 'Moldova', 'MD');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_n8ZZ27tzdZLpXYYzJnrg.j99Vh', 'Monaco', 'MC');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_A0WNyksxRnP2pPohje9k.EzId2', 'Mongolia', 'MN');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_agiiAKD4KkYxkLp4THCD.kNYwB', 'Montenegro', 'ME');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_aPuBXiefDwbwlEPHM5tP.p9WJp', 'Montserrat', 'MS');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_0WycrSusJhhicG9Yemk2.oi1N1', 'Morocco', 'MA');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_RvNlFPPKCW2BBOxsxNa1.ytBmp', 'Myanmar', 'MM');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_tsVOOfFETA8feGHliWQl.bB9a2', 'Namibia', 'NA');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_U1bvI0bWNhOSzKsiHju5.h64L7', 'Nauru', 'NR');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_3cx0nh3bGtfJgGReOmJh.01yrF', 'Nepal', 'NP');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_bd2e62IKfZ0dWs2qdyIT.wYzJp', 'Netherlands', 'NL');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_SR1xUweIu3Kv0dCgZByV.2SpU4', 'Netherlands Antilles', 'AN');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_WMW4EF7V8l8o7ovb0btm.VgKla', 'New Caledonia', 'NC');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_rJZd4AMAtpiIKoS0sVSL.I6edW', 'New Zealand', 'NZ');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_vVqheowlTlHmmUdzLGo0.9Y8yb', 'Nicaragua', 'NI');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_GpEbuw1vcbCtM78HmTcO.ecv8c', 'Niger', 'NE');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_H0n29iHJHPthSRWulUJn.tCYgF', 'Nigeria', 'NG');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_tYKl0U8LA6rzaz2IfeZu.4tswK', 'Niue', 'NU');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_quyctQMxsGIJmd6ylRjW.HdwtE', 'North Korea', 'KP');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_pF0bG2wBt2xTtsloGt0W.8Wy8V', 'Northern Mariana Islands', 'MP');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_kV2LmA4ZNHDeXQ5ZIlw2.gReqh', 'Norway', 'NO');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_xjGQMWrzKoSA5pHHQJW4.K9s39', 'Oman', 'OM');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_orNteZTY7sU730Vt43te.BPfjV', 'Pakistan', 'PK');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_Gxsd3KxMOSDd1EV0B8aJ.Lctq2', 'Palau', 'PW');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_Mlfx5cj3TTpQnzQWJtb7.bDg2D', 'Palestine', 'PS');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_wEfV2AY3rDH34CNhZNPB.ClQ0i', 'Panama', 'PA');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_H7bHQcoWCFp0tRBNdmuM.YB5Rk', 'Papua New Guinea', 'PG');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_DhtWaLjS51XRWfP19uz3.97wLC', 'Paraguay', 'PY');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_xN3U0VzmUqkuJnmEIMFH.dPLy6', 'Peru', 'PE');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_eEUBIvwozqMv1lzj8uRh.9eOER', 'Philippines', 'PH');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_vyOfZyIrQfsgstqXvzV6.wN7Bu', 'Pitcairn', 'PN');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_OkJRijWqghttmqghmk2e.TDtqO', 'Poland', 'PL');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_t3ikKg9m3CSlto3qLzwQ.TlYB0', 'Portugal', 'PT');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_lRMkjGKf2KAb0bvSSkSY.KLoyu', 'Puerto Rico', 'PR');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_ROa4xynmehpBNbovPiYK.Y0wjl', 'Qatar', 'QA');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_ibiu9mCnapeO18EobniC.ka9YE', 'Republic of the Congo', 'CG');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_9wMjn1j7iaTUfLrefsKt.nSwRG', 'Reunion', 'RE');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_YiGWJdc5zIkp6ZB8NnhO.2MIZ6', 'Romania', 'RO');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_NE0Fzrrzg5FpZtiJRdaO.Z4hsn', 'Russia', 'RU');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_lBpicVtWoA0qjArKFZUv.eUxZp', 'Rwanda', 'RW');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_pFqAMvQD2NXGHCEi9eMx.Wr3dM', 'Saint Barthelemy', 'BL');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_8XJYKdG4HdpilIIaTyv4.IYEBf', 'Saint Helena', 'SH');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_B18TfSx09RSUgXgntRZn.QtpQ6', 'Saint Lucia', 'LC');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_tE5UBjJbzEH5iMXuduc3.Mldua', 'Saint Martin', 'MF');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_ueyokhzFZ3dNatLCbaqm.fWBr0', 'Saint Pierre and Miquelon', 'PM');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_qkF8tZtSvfFmii7D9Fe4.SDFGA', 'Saint Vincent and the Grenadines', 'VC');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_RZlahNrLNSAsvvwF9NFA.qlaK1', 'Samoa', 'WS');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_LwTOYSplsu42wMkEdCuq.dRZD6', 'San Marino', 'SM');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_K2nAcp03mlzu9iAp8doH.ygHrZ', 'Sao Tome and Principe', 'ST');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_NtUJoRbwxxdXaN5Q8W09.Mb9Xx', 'Saudi Arabia', 'SA');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_hpRmYjb7q13bBX3IEHXK.kIFtr', 'Senegal', 'SN');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_T6VGBtTcbKwDNJklIJWx.jCou8', 'Serbia', 'RS');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_vPoTqLJigK3g64BNVifr.7XVRf', 'Seychelles', 'SC');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_NclXi6ADfSRQHG7RAmTj.Qipq8', 'Sierra Leone', 'SL');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_WYg6yRnbSHrIXkI6y6Mx.pWqSU', 'Singapore', 'SG');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_MkrOZSzuT7cbC6GibDdz.wNWFb', 'Sint Maarten', 'SX');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_2e3HxNWyoLiP9c8zqHxf.vcWjz', 'Slovakia', 'SK');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_sskwSLlydw2Q2ITnSyJi.nG2hf', 'Slovenia', 'SI');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_1OJfFZHDj2rRRjqQuFSE.Zfv2M', 'Solomon Islands', 'SB');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_yg7ICCLm8ClC5iwV8mAL.O9Y4U', 'Somalia', 'SO');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_nuzqLHATHbFiMe1n51sC.u6C0r', 'South Africa', 'ZA');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_aZsxpTX1oHhJ3yLTAldc.cUgBH', 'South Korea', 'KR');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_oUpE9Pvom9c32LA2FsHF.ol8Bu', 'Vietnam', 'VN');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_YBBVmCpfRp1G7BsE8GKK.fmp1y', 'Afghanistan', 'AF');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_siyOex8gTCQVfUbBktmw.2kzWY', 'Bosnia and Herzegovina', 'BA');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_YekTnZ5VsLmJyT72dqmH.dpYvm', 'Ghana', 'GH');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_VahX4pkmxOgPiYqGtuLV.oXKo7', 'Israel', 'IL');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_qDC3ZSjgGQPj1ynPJr6z.uAyh5', 'Kazakhstan', 'KZ');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_J1xGQK14dnsKkPwM1Wjq.DJoCk', 'Mozambique', 'MZ');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_1mDQfIYmzXvItC0HBhL6.H7MJn', 'Saint Kitts and Nevis', 'KN');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_EFDQ9dWbTqfhzTgNuzpL.8ZZU8', 'South Sudan', 'SS');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_czYLv01dz5PuxLhXn196.l4vAi', 'Spain', 'ES');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_dTXi50EUhWhLH30Os453.iTkgn', 'Sri Lanka', 'LK');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_nB2X0BYKnksQAhYXiR6W.IGJcM', 'Sudan', 'SD');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_lRwQWMo7Se6URSdL14GG.tBpmZ', 'Suriname', 'SR');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_E48ElhHe9tuSWKWFKaeC.dnQpx', 'Svalbard and Jan Mayen', 'SJ');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_rcLvv76az3EbuDfEe0Gr.hrFJl', 'Swaziland', 'SZ');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_9Hw09CXZixchOwvgiurm.YEmy2', 'Sweden', 'SE');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_IIXin2mxNLXekWMGIF8c.2L14G', 'Switzerland', 'CH');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_45v3SO6YLPCZyzJl5fbH.P1FCH', 'Syria', 'SY');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_HqnhBkrbtq6R4eSeIIXz.Z6PMb', 'Taiwan', 'TW');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_V4oChPJi8qFaTkE49fpI.TYaBL', 'Tajikistan', 'TJ');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_W9ORDgjzrirmgfCHNAfr.ieIOb', 'Tanzania', 'TZ');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_tR41CRfYCtuoyAxrXLGO.cjuPR', 'Thailand', 'TH');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_hQl7WZtDVmoBcarJy4k7.bzlA3', 'Togo', 'TG');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_NSNtS0SV82ykhnbbA7qQ.Fhc5e', 'Tokelau', 'TK');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_L4lHsIDxx6ZxokBFfmO2.SmXbk', 'Tonga', 'TO');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_RR6dtrufjfB29PI5XnCk.Z0hsM', 'Trinidad and Tobago', 'TT');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_cdt8IdCdulPmrhAl0uRa.8JRp6', 'Tunisia', 'TN');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_38Fvpr0xxowpOSe1lPPc.1SJvn', 'Turkey', 'TR');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_EWGHaVeKpnqdKf0ovXx4.TrPad', 'Turkmenistan', 'TM');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_Mx7YsTKZ8Jyos9cnWAgn.vRjKx', 'Turks and Caicos Islands', 'TC');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_DDbF5gLCVDdHFIkuKqnL.vTl5r', 'Tuvalu', 'TV');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_hFAquwr8JMSt67x7BX5A.yfVqg', 'U.S. Virgin Islands', 'VI');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_yQDqgRUOlw4fxgC9HADM.cGsAl', 'Uganda', 'UG');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_Y6PyDRw8Sqsy6ruUe70c.c6YjY', 'Ukraine', 'UA');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_eutGn2t9Fatx6lbU4gbJ.yctOi', 'United Arab Emirates', 'AE');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_yk3w3CS92vuc8cTNyM4e.SD7fr', 'United Kingdom', 'GB');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_LswK1cUCHTHRtJIupNvV.rnKtG', 'United States', 'US');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_BQeuhp8gQqJ2k66qv10T.3cZXJ', 'Uruguay', 'UY');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_kGjNVXmUNkQnE4glzpF8.pUsyL', 'Uzbekistan', 'UZ');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_95cESxOEi3DZJHYPQaoM.stDtG', 'Vanuatu', 'VU');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_bU29NKz6mmLyauqKwZSD.bST8O', 'Vatican', 'VA');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_1q49IkbW5ziCuZtFKkuh.koEgg', 'Venezuela', 'VE');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_bS7sjYZMlelkayT6gXqc.7hsIt', 'Wallis and Futuna', 'WF');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_gwOHnRzGG68GJ6icXrOD.8jPmP', 'Western Sahara', 'EH');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_UucYHAUJ6AnkyLZhDlzD.PikwT', 'Yemen', 'YE');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_HnVVAGKHpCEv1Lc1RVPQ.Pcynb', 'Zambia', 'ZM');
INSERT INTO public.location_country (country_id, country_name, iso_code) VALUES ('Country_yQNn6HUw9TuRC77d4Och.Tv5Ou', 'Zimbabwe', 'ZW');

INSERT INTO public.location_city (city_id, country_id, city_name) VALUES ('City_gYzvUKgI3HFCZGPLCOwR.Wyzzi', 'Country_oUpE9Pvom9c32LA2FsHF.ol8Bu', 'Thành phố Hồ Chí Minh');
INSERT INTO public.location_city (city_id, country_id, city_name) VALUES ('City_hSutGD0ZFFsqcJIeNbn1.jZwBb', 'Country_oUpE9Pvom9c32LA2FsHF.ol8Bu', 'Hà Nội');
INSERT INTO public.location_city (city_id, country_id, city_name) VALUES ('City_mTDwwU8J4qIgrrNxPxGU.4ACiH', 'Country_oUpE9Pvom9c32LA2FsHF.ol8Bu', 'Đồng Nai');
INSERT INTO public.location_city (city_id, country_id, city_name) VALUES ('City_VnCDa87QH6WjnejodQWk.XDGp1', 'Country_oUpE9Pvom9c32LA2FsHF.ol8Bu', 'Bình Dương');
INSERT INTO public.location_city (city_id, country_id, city_name) VALUES ('City_9z8YME3CyYKTQ5XX4YtU.TE8qD', 'Country_oUpE9Pvom9c32LA2FsHF.ol8Bu', 'Hải Phòng');
INSERT INTO public.location_city (city_id, country_id, city_name) VALUES ('City_95tqXFCAVtdCHKfbEFUk.jOCMw', 'Country_oUpE9Pvom9c32LA2FsHF.ol8Bu', 'Bắc Ninh');
INSERT INTO public.location_city (city_id, country_id, city_name) VALUES ('City_lGd3V0P1uqEKNy3tyLOD.My2Ls', 'Country_oUpE9Pvom9c32LA2FsHF.ol8Bu', 'Long An');
INSERT INTO public.location_city (city_id, country_id, city_name) VALUES ('City_DRFql62Zk2xDX3mlcZmJ.nyFuB', 'Country_oUpE9Pvom9c32LA2FsHF.ol8Bu', 'Khánh Hòa');
INSERT INTO public.location_city (city_id, country_id, city_name) VALUES ('City_ln2hc64i2BQhdMP36CQV.AryDU', 'Country_oUpE9Pvom9c32LA2FsHF.ol8Bu', 'Bình Định');
INSERT INTO public.location_city (city_id, country_id, city_name) VALUES ('City_lFnRbFpPvGGvvCFBu4Wy.tfniA', 'Country_oUpE9Pvom9c32LA2FsHF.ol8Bu', 'An Giang');
INSERT INTO public.location_city (city_id, country_id, city_name) VALUES ('City_onbxCCNrl9vfqVUjnpLh.eN6aK', 'Country_oUpE9Pvom9c32LA2FsHF.ol8Bu', 'Quảng Ngãi');
INSERT INTO public.location_city (city_id, country_id, city_name) VALUES ('City_Kcspv6ZTXg7IQLHMjUIz.Ov8dW', 'Country_oUpE9Pvom9c32LA2FsHF.ol8Bu', 'Tây Ninh');
INSERT INTO public.location_city (city_id, country_id, city_name) VALUES ('City_kypdjCShPCVarih46xgE.4ZxbR', 'Country_oUpE9Pvom9c32LA2FsHF.ol8Bu', 'Thái Bình');
INSERT INTO public.location_city (city_id, country_id, city_name) VALUES ('City_IrWTz3XiOd0wc7HJdABA.UCpNb', 'Country_oUpE9Pvom9c32LA2FsHF.ol8Bu', 'Đồng Tháp');
INSERT INTO public.location_city (city_id, country_id, city_name) VALUES ('City_gtzOHva9ESnUKTlOxBJ4.yzWRb', 'Country_oUpE9Pvom9c32LA2FsHF.ol8Bu', 'Gia Lai');
INSERT INTO public.location_city (city_id, country_id, city_name) VALUES ('City_mE4rIEnzukfIkpQIlZen.7sets', 'Country_oUpE9Pvom9c32LA2FsHF.ol8Bu', 'Hưng Yên');
INSERT INTO public.location_city (city_id, country_id, city_name) VALUES ('City_1TAioAkMJLpFl2hzeYVC.hz8av', 'Country_oUpE9Pvom9c32LA2FsHF.ol8Bu', 'Hà Tĩnh');
INSERT INTO public.location_city (city_id, country_id, city_name) VALUES ('City_iyy3ISBzZm6zgiRiVqtq.HTYyT', 'Country_oUpE9Pvom9c32LA2FsHF.ol8Bu', 'Bình Thuận');
INSERT INTO public.location_city (city_id, country_id, city_name) VALUES ('City_BPIux23juY4whv3jxxCK.7l5uF', 'Country_oUpE9Pvom9c32LA2FsHF.ol8Bu', 'Nam Định');
INSERT INTO public.location_city (city_id, country_id, city_name) VALUES ('City_VkNDQtyh8R60ZBxxm89f.MfXQE', 'Country_oUpE9Pvom9c32LA2FsHF.ol8Bu', 'Phú Thọ');
INSERT INTO public.location_city (city_id, country_id, city_name) VALUES ('City_xQrxI5PgYILFbWat3BQA.mQ0ki', 'Country_oUpE9Pvom9c32LA2FsHF.ol8Bu', 'Bình Phước');
INSERT INTO public.location_city (city_id, country_id, city_name) VALUES ('City_04qIU4hiUymapnS3Ivl5.NN1Mg', 'Country_oUpE9Pvom9c32LA2FsHF.ol8Bu', 'Cà Mau');
INSERT INTO public.location_city (city_id, country_id, city_name) VALUES ('City_yK9VVRwC3vbV0HU28SaW.FJpa5', 'Country_oUpE9Pvom9c32LA2FsHF.ol8Bu', 'Sóc Trăng');
INSERT INTO public.location_city (city_id, country_id, city_name) VALUES ('City_OINV5R5NhnNv1A9Unni5.snkb5', 'Country_oUpE9Pvom9c32LA2FsHF.ol8Bu', 'Thừa Thiên - Huế');
INSERT INTO public.location_city (city_id, country_id, city_name) VALUES ('City_6WsooIdtLnc7MiKpMnMX.v8zdC', 'Country_oUpE9Pvom9c32LA2FsHF.ol8Bu', 'Sơn La');
INSERT INTO public.location_city (city_id, country_id, city_name) VALUES ('City_YxTzM3piWKkm4c8mYcRn.jO4NO', 'Country_oUpE9Pvom9c32LA2FsHF.ol8Bu', 'Ninh Bình');
INSERT INTO public.location_city (city_id, country_id, city_name) VALUES ('City_kYZ0sMaKlgIWOmv38sVn.nA0kv', 'Country_oUpE9Pvom9c32LA2FsHF.ol8Bu', 'Vĩnh Long');
INSERT INTO public.location_city (city_id, country_id, city_name) VALUES ('City_VQr0fm8mbSWB6CeetsJL.G8WTW', 'Country_oUpE9Pvom9c32LA2FsHF.ol8Bu', 'Trà Vinh');
INSERT INTO public.location_city (city_id, country_id, city_name) VALUES ('City_L8UCeJWw01hQuQt72Bvt.8UFou', 'Country_oUpE9Pvom9c32LA2FsHF.ol8Bu', 'Hà Nam');
INSERT INTO public.location_city (city_id, country_id, city_name) VALUES ('City_hhKUplUMNh343omE48C6.hDuux', 'Country_oUpE9Pvom9c32LA2FsHF.ol8Bu', 'Lào Cai');
INSERT INTO public.location_city (city_id, country_id, city_name) VALUES ('City_5MK4yNX8kESt3iwM3Djz.sUihw', 'Country_oUpE9Pvom9c32LA2FsHF.ol8Bu', 'Bến Tre');
INSERT INTO public.location_city (city_id, country_id, city_name) VALUES ('City_NlDzmVmel6iw2WGQ93sM.H8B7e', 'Country_oUpE9Pvom9c32LA2FsHF.ol8Bu', 'Hòa Bình');
INSERT INTO public.location_city (city_id, country_id, city_name) VALUES ('City_Xo9kXEwvHBTCxJszcG9a.rU11t', 'Country_oUpE9Pvom9c32LA2FsHF.ol8Bu', 'Bạc Liêu');
INSERT INTO public.location_city (city_id, country_id, city_name) VALUES ('City_ClvxT01I0NpfEDr8nyoq.TMS2v', 'Country_oUpE9Pvom9c32LA2FsHF.ol8Bu', 'Phú Yên');
INSERT INTO public.location_city (city_id, country_id, city_name) VALUES ('City_42i7W3XhyAEtsMMQekrO.OWRwO', 'Country_oUpE9Pvom9c32LA2FsHF.ol8Bu', 'Quảng Bình');
INSERT INTO public.location_city (city_id, country_id, city_name) VALUES ('City_1iuUGvV7NyMLdrhNixR1.3cv46', 'Country_oUpE9Pvom9c32LA2FsHF.ol8Bu', 'Lạng Sơn');
INSERT INTO public.location_city (city_id, country_id, city_name) VALUES ('City_JoLBraY398vA9jQBp0YO.n1Hzk', 'Country_oUpE9Pvom9c32LA2FsHF.ol8Bu', 'Hậu Giang');
INSERT INTO public.location_city (city_id, country_id, city_name) VALUES ('City_Sc6ibsXTBixpjZXIshKX.qK5xT', 'Country_oUpE9Pvom9c32LA2FsHF.ol8Bu', 'Đắk Nông');
INSERT INTO public.location_city (city_id, country_id, city_name) VALUES ('City_7OfRxgnSTNNYReY47vAk.WluU9', 'Country_oUpE9Pvom9c32LA2FsHF.ol8Bu', 'Tuyên Quang');
INSERT INTO public.location_city (city_id, country_id, city_name) VALUES ('City_uiIWxM7YM6xKkgowKR4B.Sg3Kz', 'Country_oUpE9Pvom9c32LA2FsHF.ol8Bu', 'Quảng Trị');
INSERT INTO public.location_city (city_id, country_id, city_name) VALUES ('City_BZtUUssehYzEhf44JMgA.uLiuC', 'Country_oUpE9Pvom9c32LA2FsHF.ol8Bu', 'Yên Bái');
INSERT INTO public.location_city (city_id, country_id, city_name) VALUES ('City_BGCxr9gNsyjMIiudbCeR.M0WVV', 'Country_oUpE9Pvom9c32LA2FsHF.ol8Bu', 'Ninh Thuận');
INSERT INTO public.location_city (city_id, country_id, city_name) VALUES ('City_UecBNiChU33sa39ZftRx.A7ANL', 'Country_oUpE9Pvom9c32LA2FsHF.ol8Bu', 'Hà Giang');
INSERT INTO public.location_city (city_id, country_id, city_name) VALUES ('City_7YEe476876gZ9PbYxjNx.bKCiI', 'Country_oUpE9Pvom9c32LA2FsHF.ol8Bu', 'Kon Tum');
INSERT INTO public.location_city (city_id, country_id, city_name) VALUES ('City_GE5gslweqdTb9MyhiQXn.fSHPr', 'Country_oUpE9Pvom9c32LA2FsHF.ol8Bu', 'Điện Biên');
INSERT INTO public.location_city (city_id, country_id, city_name) VALUES ('City_p948QpCdpSg7Cm5fKn2F.JhkcC', 'Country_oUpE9Pvom9c32LA2FsHF.ol8Bu', 'Lai Châu');
INSERT INTO public.location_city (city_id, country_id, city_name) VALUES ('City_CeF2SfTIXvL4w1EpszC2.YHy2a', 'Country_oUpE9Pvom9c32LA2FsHF.ol8Bu', 'Cao Bằng');
INSERT INTO public.location_city (city_id, country_id, city_name) VALUES ('City_xsejTJupT2OWym1ODjkM.lcNK6', 'Country_oUpE9Pvom9c32LA2FsHF.ol8Bu', 'Bắc Kạn');
INSERT INTO public.location_city (city_id, country_id, city_name) VALUES ('City_8W3DXWmlMwR1NdgZ8Jaw.Uvvqu', 'Country_oUpE9Pvom9c32LA2FsHF.ol8Bu', 'Bà Rịa-Vũng Tàu');
INSERT INTO public.location_city (city_id, country_id, city_name) VALUES ('City_pJZ0k5BEe1k0HnV5PjNJ.OXqMG', 'Country_oUpE9Pvom9c32LA2FsHF.ol8Bu', 'Thanh Hóa');
INSERT INTO public.location_city (city_id, country_id, city_name) VALUES ('City_24EYkZ2Jgyz5odP0PUA8.Z6I6O', 'Country_oUpE9Pvom9c32LA2FsHF.ol8Bu', 'Quảng Ninh');
INSERT INTO public.location_city (city_id, country_id, city_name) VALUES ('City_DFtIQt0kErEOQ4qHQHh7.eYMZt', 'Country_oUpE9Pvom9c32LA2FsHF.ol8Bu', 'Nghệ An');
INSERT INTO public.location_city (city_id, country_id, city_name) VALUES ('City_KQn6BB4cU472CUay5oWW.yrUfc', 'Country_oUpE9Pvom9c32LA2FsHF.ol8Bu', 'Hải Dương');
INSERT INTO public.location_city (city_id, country_id, city_name) VALUES ('City_xOOpZFziymNGy3TNLMQz.JjTJg', 'Country_oUpE9Pvom9c32LA2FsHF.ol8Bu', 'Cần Thơ');
INSERT INTO public.location_city (city_id, country_id, city_name) VALUES ('City_th7WRhUZiVGJGfZyA42a.CnChT', 'Country_oUpE9Pvom9c32LA2FsHF.ol8Bu', 'Thái Nguyên');
INSERT INTO public.location_city (city_id, country_id, city_name) VALUES ('City_8jr2Zmj6ztInsFYqEt8o.scdQI', 'Country_oUpE9Pvom9c32LA2FsHF.ol8Bu', 'Vĩnh Phúc');
INSERT INTO public.location_city (city_id, country_id, city_name) VALUES ('City_W5EXOcr2Pp9offZyWzxe.5ZO0c', 'Country_oUpE9Pvom9c32LA2FsHF.ol8Bu', 'Quảng Nam');
INSERT INTO public.location_city (city_id, country_id, city_name) VALUES ('City_Eovijy5rV2hF1aO6w929.2vB7g', 'Country_oUpE9Pvom9c32LA2FsHF.ol8Bu', 'Đà Nẵng');
INSERT INTO public.location_city (city_id, country_id, city_name) VALUES ('City_d4sMY8oCbynQIoM2LHqu.TDI5D', 'Country_oUpE9Pvom9c32LA2FsHF.ol8Bu', 'Bắc Giang');
INSERT INTO public.location_city (city_id, country_id, city_name) VALUES ('City_8tTCDiQudwPdDMsqncqc.CKJiv', 'Country_oUpE9Pvom9c32LA2FsHF.ol8Bu', 'Kiên Giang');
INSERT INTO public.location_city (city_id, country_id, city_name) VALUES ('City_2vrPSXgJjaghBwa1i6UU.TEonZ', 'Country_oUpE9Pvom9c32LA2FsHF.ol8Bu', 'Tiền Giang');
INSERT INTO public.location_city (city_id, country_id, city_name) VALUES ('City_Oo1v8FifWaGRzWohvWbu.AGM9m', 'Country_oUpE9Pvom9c32LA2FsHF.ol8Bu', 'Đắk Lắk');
INSERT INTO public.location_city (city_id, country_id, city_name) VALUES ('City_gPZfndHedjoua8zR0K0J.NcJsv', 'Country_oUpE9Pvom9c32LA2FsHF.ol8Bu', 'Lâm Đồng');

INSERT INTO public.location_city_division (division_id, city_id, division_name) VALUES ('Div_KnOFp35XHRTuBLB0tYDL.GqZAz', 'City_8W3DXWmlMwR1NdgZ8Jaw.Uvvqu', 'Châu Đức');
INSERT INTO public.location_city_division (division_id, city_id, division_name) VALUES ('Div_VfMeIsKxpG5seqRZixKK.JcCBg', 'City_8W3DXWmlMwR1NdgZ8Jaw.Uvvqu', 'Côn Đảo');
INSERT INTO public.location_city_division (division_id, city_id, division_name) VALUES ('Div_JfzZKhrUIEGNWq3wgUlg.1bEy4', 'City_8W3DXWmlMwR1NdgZ8Jaw.Uvvqu', 'Đất Đỏ');
INSERT INTO public.location_city_division (division_id, city_id, division_name) VALUES ('Div_tFFffKUJIv4JYWpTPUuQ.zugBb', 'City_8W3DXWmlMwR1NdgZ8Jaw.Uvvqu', 'Long Điền');
INSERT INTO public.location_city_division (division_id, city_id, division_name) VALUES ('Div_3fXkOC4pTRNK0VkM61uY.ovVam', 'City_8W3DXWmlMwR1NdgZ8Jaw.Uvvqu', 'Xuyên Mộc');
INSERT INTO public.location_city_division (division_id, city_id, division_name) VALUES ('Div_hClxQqXZvRYUoWLQsfHS.PjKnE', 'City_8W3DXWmlMwR1NdgZ8Jaw.Uvvqu', 'Phú Mỹ');
INSERT INTO public.location_city_division (division_id, city_id, division_name) VALUES ('Div_NiCoeYniHxMfGpnrNHna.W2I9W', 'City_8W3DXWmlMwR1NdgZ8Jaw.Uvvqu', 'TP. Bà Rịa');
INSERT INTO public.location_city_division (division_id, city_id, division_name) VALUES ('Div_Heh3nF85c4pBqgSpV6En.s05U2', 'City_8W3DXWmlMwR1NdgZ8Jaw.Uvvqu', 'TP. Vũng Tàu');

INSERT INTO public.location_city_sub_division (sub_division_id, division_id, sub_division_name) VALUES ('SubDiv_7kcY7rvgiefQydn2o0u7.1Hu8z', 'Div_Heh3nF85c4pBqgSpV6En.s05U2', 'Phường 1');
INSERT INTO public.location_city_sub_division (sub_division_id, division_id, sub_division_name) VALUES ('SubDiv_joF9DPK5Vitg7wBBH0ys.yyVXH', 'Div_Heh3nF85c4pBqgSpV6En.s05U2', 'Phường 2');
INSERT INTO public.location_city_sub_division (sub_division_id, division_id, sub_division_name) VALUES ('SubDiv_AkOiC6faMnhrQev8i9eR.TbTLD', 'Div_Heh3nF85c4pBqgSpV6En.s05U2', 'Phường 3');
INSERT INTO public.location_city_sub_division (sub_division_id, division_id, sub_division_name) VALUES ('SubDiv_kAW9J3v1w7gwLqbVWhCz.Jfdod', 'Div_Heh3nF85c4pBqgSpV6En.s05U2', 'Phường 4');
INSERT INTO public.location_city_sub_division (sub_division_id, division_id, sub_division_name) VALUES ('SubDiv_Ce0c1SZ03UDKGf0YfSQe.keWcX', 'Div_Heh3nF85c4pBqgSpV6En.s05U2', 'Phường 5');
INSERT INTO public.location_city_sub_division (sub_division_id, division_id, sub_division_name) VALUES ('SubDiv_HAruvDzj1mxftdsOwDdV.13EW8', 'Div_Heh3nF85c4pBqgSpV6En.s05U2', 'Phường 7');
INSERT INTO public.location_city_sub_division (sub_division_id, division_id, sub_division_name) VALUES ('SubDiv_QXEou2nugrWegaOwc891.o7h6X', 'Div_Heh3nF85c4pBqgSpV6En.s05U2', 'Phường 8');
INSERT INTO public.location_city_sub_division (sub_division_id, division_id, sub_division_name) VALUES ('SubDiv_uxqpZ8JAGSVJoeg35gXS.UBK5H', 'Div_Heh3nF85c4pBqgSpV6En.s05U2', 'Phường 9');
INSERT INTO public.location_city_sub_division (sub_division_id, division_id, sub_division_name) VALUES ('SubDiv_YScZfbeJjCbrlPbuyLEl.S2NwI', 'Div_Heh3nF85c4pBqgSpV6En.s05U2', 'Phường 10');
INSERT INTO public.location_city_sub_division (sub_division_id, division_id, sub_division_name) VALUES ('SubDiv_vK0KuGFOkPZCSzQTZpKh.q31jt', 'Div_Heh3nF85c4pBqgSpV6En.s05U2', 'Phường 11');
INSERT INTO public.location_city_sub_division (sub_division_id, division_id, sub_division_name) VALUES ('SubDiv_Z0M8VSbH6ESDtINZ5szi.s7E00', 'Div_Heh3nF85c4pBqgSpV6En.s05U2', 'Phường 12');
INSERT INTO public.location_city_sub_division (sub_division_id, division_id, sub_division_name) VALUES ('SubDiv_3JmADxHrJLJfSfgXuQ6o.7AVBx', 'Div_Heh3nF85c4pBqgSpV6En.s05U2', 'Thắng Nhất');
INSERT INTO public.location_city_sub_division (sub_division_id, division_id, sub_division_name) VALUES ('SubDiv_lxLACI9K2utqB0x5LRq7.cDvLd', 'Div_Heh3nF85c4pBqgSpV6En.s05U2', 'Thắng Nhì');
INSERT INTO public.location_city_sub_division (sub_division_id, division_id, sub_division_name) VALUES ('SubDiv_PZmV57Pp4PV4kgnHB0Mf.VrXKM', 'Div_Heh3nF85c4pBqgSpV6En.s05U2', 'Thắng Tam');
INSERT INTO public.location_city_sub_division (sub_division_id, division_id, sub_division_name) VALUES ('SubDiv_B6cw2WRM5GnayPJrzY5B.dwvAT', 'Div_Heh3nF85c4pBqgSpV6En.s05U2', 'Nguyễn An Ninh');
INSERT INTO public.location_city_sub_division (sub_division_id, division_id, sub_division_name) VALUES ('SubDiv_rfJdzyGA8qd0cb1ZsbzT.LBtb5', 'Div_Heh3nF85c4pBqgSpV6En.s05U2', 'Rạch Dừa');
INSERT INTO public.location_city_sub_division (sub_division_id, division_id, sub_division_name) VALUES ('SubDiv_NDCaQrfiVnHbU0SCNqo9.Zjk6h', 'Div_Heh3nF85c4pBqgSpV6En.s05U2', 'Xã Long Sơn');